services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=1000      # Replace with your user ID
      - PGID=1000      # Replace with your group ID
      - TZ=Europe/London # Set your timezone LONDON FTW
      - DUPLICATI__WEBSERVICE_PASSWORD=${PASSWORD}
      - SETTINGS_ENCRYPTION_KEY= ${ENCRYPTION_KEY} # Optional but recommended
    volumes:
      - ./config:/config       # Stores Duplicati settings and database
      - ./backups:/backups     # Local destination for backup files
      - root-omv:/source:ro #:ro #i added this for my open media vault, probably change the vol if your stealing this
    ports: 
      - ${PORT:-8200}:${PORT:-8200}              # Web interface access
    restart: unless-stopped   
    
    deploy:
      resources:
        limits:
            memory: ${HARDMEMORY:-512M}
            #hard memory limit

            cpus: ${CPU:-1}
            #cpu usage limit

   


   volumes:
    root-omv:
      external: true
      