#use proper versioning
# se the latest stable versioning
#keep services modular
#use env variables for secrets and service settings  DB_HOST=${DB_HOST}

name: ${SERVICENAME}

services:

  navidrome:
    image: deluan/navidrome:latest
    container_name: navi
    restart: unless-stopped
    ports:
      - "${PORT:-4533}:${PORT:-4533}"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - ND_SCANINTERVAL=1m
      - ND_LOGLEVEL=info
      - ND_PORT=${PORT:-4533}
      - ND_TRANSCODINGCACHESIZE=100MB
      - ND_SESSIONTIMEOUT=24h
      - ND_DEFAULTDOWNLOADABLESHARE=true
      - ND_ENABLEINSIGHTSCOLLECTOR=false
      - ND_PROMETHEUS_ENABLED=false

    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --proxy off http://localhost:4533/ping || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    volumes:
      #- navi_vol:/data
     # - omv-navi:/music:ro
      - omv-navi:/music:ro
      - omv-navi-DB:/data

      #- ./music:/music:ro
    #Resource limits cpu/memory
    deploy:
      resources:
        limits:
            memory: ${HARDMEMORY:-256M}
            #hard memory limit
            cpus: ${CPU:-1.0}

        reservations:
          memory: ${SOFTMEMEMORY}
          #soft memory limit



volumes:
  omv-navi:
    driver_opts:
      type: cifs
      o: 'iocharset=utf8,username=Mineswat,password=Komaru1!,rw' # change to `ro` if read only desired
      device: "//192.168.0.88/Root/Media/Media/Music"

  omv-navi-DB:

#make another volume