
#dattabayo music!!! 
services:

  navidrome:
    image: deluan/navidrome:latest
    container_name: navi
    restart: unless-stopped
    ports:
      - "${PORT:4533}:${PORT:4533}"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - ND_SCANINTERVAL=1m
      - ND_LOGLEVEL=info
      - ND_PORT=4533
      - ND_TRANSCODINGCACHESIZE=100MB
      - ND_SESSIONTIMEOUT=24h
      - ND_DEFAULTDOWNLOADABLESHARE=true
      - ND_ENABLEINSIGHTSCOLLECTOR=false
    volumes:
      #- navi_vol:/data
      - omvNetwork:/music:ro
      - omvNetwork:/appdata/navidrome/data

      #- ./music:/music:ro


volumes:
 # navi_vol:

  omvNetwork:
    external: true