---
services:
  qbittorrent:
    image: linuxserver/qbittorrent:libtorrentv1-version-5.2.2_v1.2.20
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=${TORRENT_PORT:-6887}
      
    volumes:
      - tconfig:/config
      - Q-OMV:/Downloads #optional
    ports:
      - 8080:8080
      - ${TORRENT_PORT:-6887}:${TORRENT_PORT:-6887}
      - ${TORRENT_PORT:-6887}:${TORRENT_PORT:-6887}/udp
    stop_grace_period: "10s" #optional
    restart: unless-stopped
    network_mode: host

volumes:
 tconfig:
 Q-OMV:
  driver_opts:
    type: cifs
    o: 'iocharset=utf8,username=Mineswat,password=Komaru1!,rw' # change to `ro` if read only desired
    device: "//192.168.0.88/Root/Downloads"
