---
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=14972
    volumes:
      - tconfig:/config
      - Root-OMV:/Downloads #optional
    ports:
      - 8080:8080
      - 6887:6887
      - 6887:6887/udp
    stop_grace_period: "10s" #optional
    restart: unless-stopped

volumes:
 tconfig:
 Root-OMV:
   external: true
