

#dattabayo music!!! 
services:

  homarr:
    image: ghcr.io/homarr-labs/homarr:latest
    container_name: homarr
    restart: unless-stopped
    ports:
      - "7575:7575"
    environment:
      - SECRET_ENCRYPTION_KEY=98a523a191e5387b8055cd3359db40eac626377bed2cc71ef509318da9557838

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - homarr_vol:/appdata

    deploy:
      resources:
        limits:
            memory: ${HARDMEMORY:-256M}
            #hard memory limit
            cpus: 0.01





volumes:
  homarr_vol: